export const ttsAudioManifest = {
  'drowsiness-rest-area-2-agent': '/audio/tts/agent/잠시 쉬어가면 좋겠습니다. 가까운 쉼터를 찾아드릴까요_.mp3',
  'drowsiness-rest-area-3-user': '/audio/tts/user/02_가까운_졸음쉼터로_안내해줘.mp3',
  'drowsiness-rest-area-4-agent': '/audio/tts/agent/가장 가까운 졸음쉼터를 찾았습니다. 현재 경로에서 2.4km 거리이고 4분 뒤 도착할 수 있습니다.mp3',
  'drowsiness-rest-area-5-user': '/audio/tts/user/03_응_그곳으로_안내해줘.mp3',
  'drowsiness-rest-area-6-agent': '/audio/tts/agent/가장 가까운 졸음쉼터로 안내를 시작합니다.mp3',
  'drowsiness-rest-area-7-agent': '/audio/tts/agent/경로를 변경했습니다. 안전하게 이동해 주세요.mp3',
  'drowsiness-rest-area-8-agent': '/audio/tts/agent/필요하면 다시 불러 주세요.mp3',
  'fatigue-music-2-agent': '/audio/tts/agent/잠깐 리듬을 바꿔볼까요_ 밝은 음악을 준비해드릴게요.mp3',
  'fatigue-music-3-user': '/audio/tts/user/04_밝은_음악_틀어줘.mp3',
  'fatigue-music-4-agent': '/audio/tts/agent/밝은 팝 플레이리스트를 준비했습니다. 가볍게 들으며 이어가 보세요.mp3',
  'fatigue-music-5-user': '/audio/tts/user/05_좋아_그_음악_틀어줘.mp3',
  'fatigue-music-6-agent': '/audio/tts/agent/음악을 재생합니다.mp3',
  'fatigue-music-7-agent': '/audio/tts/agent/재생 중인 음악은 아래에서 확인할 수 있습니다.mp3',
  'fatigue-music-8-agent': '/audio/tts/agent/음악은 계속 재생해 둘게요.mp3',
  'phone-message-2-agent': '/audio/tts/agent/운전 중에는 제가 대신 도와드릴게요. 메시지를 보낼까요_.mp3',
  'phone-message-3-user': '/audio/tts/user/01_엄마한테_10분_늦는다고_문자_보내줘.mp3',
  'phone-message-4-agent': '/audio/tts/agent/엄마에게 보낼 문자를 확인해 주세요. 내용은 도착이 10분 정도 늦을 것 같아요입니다.mp3',
  'phone-message-5-agent': '/audio/tts/agent/아래 내용으로 문자를 보낼까요_.mp3',
  'phone-message-6-user': '/audio/tts/user/06_보내줘.mp3',
  'phone-message-7-agent': '/audio/tts/agent/문자 전송이 완료됐습니다.mp3',
  'phone-message-8-agent': '/audio/tts/agent/필요하면 다시 도와드릴게요.mp3',
  'fatigue-window-2-agent': '/audio/tts/agent/실내 공기를 조금 바꿔볼까요_ 창문을 살짝 열 수 있어요.mp3',
  'fatigue-window-3-user': '/audio/tts/user/07_창문_살짝_열어줘.mp3',
  'fatigue-window-4-agent': '/audio/tts/agent/운전석 창문을 20퍼센트 정도 열어 환기할 수 있습니다.mp3',
  'fatigue-window-5-user': '/audio/tts/user/08_응_그렇게_해줘.mp3',
  'fatigue-window-6-agent': '/audio/tts/agent/창문을 살짝 열어 환기하겠습니다.mp3',
  'fatigue-window-7-agent': '/audio/tts/agent/환기를 시작했습니다.mp3',
  'fatigue-window-8-agent': '/audio/tts/agent/필요하면 다시 도와드릴게요_2.mp3',
  'fatigue-conversation-2-agent': '/audio/tts/agent/잠깐 기분 전환해 볼까요_ 짧은 이야기를 들려드릴 수 있어요.mp3',
  'fatigue-conversation-3-user': '/audio/tts/user/09_짧은_이야기_해줘.mp3',
  'fatigue-conversation-4-agent': '/audio/tts/agent/짧은 퀴즈를 추천합니다. 1분 정도 가볍게 집중을 환기할 수 있습니다.mp3',
  'fatigue-conversation-5-user': '/audio/tts/user/10_좋아_퀴즈_시작해줘.mp3',
  'fatigue-conversation-6-agent': '/audio/tts/agent/짧은 퀴즈 하나 드릴게요. 서울에서 가장 긴 다리는 무엇일까요_.mp3',
  'fatigue-conversation-7-agent': '/audio/tts/agent/생각나시면 답을 말씀해 주세요.mp3',
  'long-drive-rest-area-2-agent': '/audio/tts/agent/잠시 쉬어가면 좋겠습니다. 경로 근처 휴게소를 찾아드릴까요_.mp3',
  'long-drive-rest-area-3-user': '/audio/tts/user/11_가까운_휴게소_찾아줘.mp3',
  'long-drive-rest-area-4-agent': '/audio/tts/agent/경로에서 가까운 휴게소를 찾았습니다. 잠시 쉬어가기 좋은 위치입니다.mp3',
  'long-drive-rest-area-5-user': '/audio/tts/user/12_응_그_휴게소로_안내해줘.mp3',
  'long-drive-rest-area-6-agent': '/audio/tts/agent/경로에서 가까운 휴게소로 안내를 시작합니다.mp3',
  'long-drive-rest-area-7-agent': '/audio/tts/agent/경로를 변경했습니다. 안전하게 이동해 주세요_2.mp3',
  'long-drive-rest-area-8-agent': '/audio/tts/agent/필요하면 다시 불러 주세요_2.mp3',
  'distraction-voice-guide-2-agent': '/audio/tts/agent/전방을 확인해 주세요. 안내는 음성으로 더 자세히 도와드릴게요.mp3',
  'distraction-voice-guide-3-user': '/audio/tts/user/13_알겠어_음성_안내_켜줘.mp3',
  'distraction-voice-guide-4-agent': '/audio/tts/agent/음성 안내를 강화하겠습니다.mp3',
  'distraction-voice-guide-5-agent': '/audio/tts/agent/음성 안내가 강화되었습니다.mp3',
  'distraction-voice-guide-6-agent': '/audio/tts/agent/필요하면 다시 도와드릴게요_3.mp3',
  'route-search-voice-0-agent': '/audio/tts/agent/목적지 검색을 시작합니다.mp3',
  'route-search-voice-1-agent': '/audio/tts/agent/어디로 안내할까요_.mp3',
  'route-search-voice-2-user': '/audio/tts/user/14_세종대학교로_안내해줘.mp3',
  'route-search-voice-3-agent': '/audio/tts/agent/세종대학교를 찾았습니다.mp3',
  'route-search-voice-4-agent': '/audio/tts/agent/세종대학교로 안내를 시작할까요_.mp3',
  'route-search-voice-5-user': '/audio/tts/user/15_응_시작해.mp3',
  'route-search-voice-6-agent': '/audio/tts/agent/주행 화면으로 돌아갑니다.mp3',
  'route-search-voice-7-agent': '/audio/tts/agent/세종대학교로 안내를 시작합니다.mp3',
  'safety-report-0-agent': '/audio/tts/agent/주행이 종료되었습니다.mp3',
  'safety-report-1-agent': '/audio/tts/agent/오늘의 운전 리포트를 확인해 보시겠어요_.mp3',
  'safety-report-2-user': '/audio/tts/user/16_보여줘.mp3',
  'safety-report-3-agent': '/audio/tts/agent/안전 운전 리포트를 보여드릴게요.mp3',
  'safety-report-4-agent': '/audio/tts/agent/오늘의 안전 점수는 82점입니다. 야간 구간에서 졸음 징후가 있었습니다.mp3',
  'settings-check-0-agent': '/audio/tts/agent/설정 화면을 보여드릴게요.mp3',
  'settings-check-1-agent': '/audio/tts/agent/에이전트 개입 강도는 낮음, 보통, 높음 중에서 조정할 수 있습니다.mp3',
  'settings-check-2-agent': '/audio/tts/agent/졸음, 주의 분산, 휴대폰 사용, 장시간 운전 감지를 각각 켜고 끌 수 있습니다.mp3',
  'settings-check-3-agent': '/audio/tts/agent/음성 안내, 화면 경고, 경고음, 진동 알림을 조정할 수 있습니다.mp3',
  'settings-check-4-agent': '/audio/tts/agent/위치, 연락처, 메시지, 메일, 음악 앱 권한 상태를 확인할 수 있습니다.mp3',
  'settings-check-5-agent': '/audio/tts/agent/음악 서비스와 차량 제어 연결 상태도 이 화면에서 확인할 수 있습니다.mp3',
} as const

export type TtsAudioKey = keyof typeof ttsAudioManifest
